## You should change each of the following fields
## to customize your blog

title: ANNA'S ANALYTICS
description: "A statistics girl's guide to all things sports. Posts use R, Python, Tableau, and more! I try to make everything reproducible so you can follow along too :)"
author: Anna Fellars
author_description: |
  Hey! I'm Anna, and I'm studying applied analytics at BYU. I've always had a passion for both sports and data, so this blog is my way of combining the two things I love and sharing them with you!  

  Ever since I was little, I've loved sports. From ballet, soccer, volleyball, and golf, I kept busy learning as many as I could.  As I got older, it became clear that tennis was my true love, and I dedicated all of high school to competing.  I went on to win two state championships and even coached for a few years in college.  I also competed in golf, where my team won state twice as well.  

  Even though I played individual sports, I was always supported by teammates, coaches, and family who pushed me to be my best.  Sports have shaped me into who I am today, and I want to help others find their passion the way I did.
  
  Because I was never the strongest, tallest, or fastest athlete, I had to be the most strategic.  I treated tennis like a game of chess, constantly adapting my strategy to target weaknesses.  In golf, I carried a notebook and collected data after every shot to optimize my game plan.  

  I believe analytics are the future of sports—helping fans understand the game like insiders,  giving young athletes the most effective strategies, and ensuring professionals have the data they need to stay healthy and perform at their best.  The possibilities are limitless, and I'm determined to advance the field to strengthen athletes, teams, and fans.  

  When I'm not playing, watching, or analyzing sports, I enjoy reading, cooking, hiking, and watching chick flicks.  I'm incredibly grateful for the friends and family who always believe in me and push me to go after my dreams.  I hope you enjoy my blog, and please reach out if you have any ideas or opportunities!  

  **XOXO, Anna**
 

url: https://annafellars.github.io ## change this to https://yourusername.github.io
baseurl: /annablog ## change this to the name of your blog repository
header_image: /assets/img/background.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  annafellars ## required
    twitter: 
    facebook: 
    email: anna@fellars.com
    linkedin: https://www.linkedin.com/in/anna-fellars/
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




