## You should change each of the following fields
## to customize your blog

title: ANNA'S ANALYTICS
description: "A statistics girl's guide to all things sports."
author: Anna Fellars
author_description: "Hey! I'm Anna and I'm a senior studying applied analytics. I've always had a passion for sports and analytics so this blog is a chance for me to combine the two things I love and share it with you!" 

url: https://annafellars.github.io ## change this to https://yourusername.github.io
baseurl: /annablog ## change this to the name of your blog repository
header_image: /assets/img/sports_background.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  annafellars ## required
    twitter: 
    facebook: 
    email: anna@fellars.com
    linkedin: Anna Fellars
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




